# Archivo de Configuración Stellar - Catálogo de ErnestoCripto
HOME_DOMAIN = "ernestocripto.github.io"

[[CURRENCIES]]
code = "CRIPTO01"
issuer = "GAVOA6QBBSDKH3NMD2LQIJBXBT3CZPG4CHFGMNDZ4PJ63T7XVK5VKGF6"
display_decimals = 0
name = "Talk Cripto"
image = "https://raw.githubusercontent.com/ernestocripto/SkillGraph/main/assets/CRIPTO01.png"
desc = "Plática Cripto en la Universidad"

[[CURRENCIES]]
code = "MKT101"
issuer = "GAVOA6QBBSDKH3NMD2LQIJBXBT3CZPG4CHFGMNDZ4PJ63T7XVK5VKGF6"
display_decimals = 0
name = "Fundamentos de Marketing"
image = "https://raw.githubusercontent.com/ernestocripto/SkillGraph/main/assets/MKT101.png"
desc = "Introducción al Marketing Web3"

[[CURRENCIES]]
code = "STELLAR101"
issuer = "GAVOA6QBBSDKH3NMD2LQIJBXBT3CZPG4CHFGMNDZ4PJ63T7XVK5VKGF6"
display_decimals = 0
name = "Stellar Blockchain"
image = "https://raw.githubusercontent.com/ernestocripto/SkillGraph/main/assets/STELLAR101.png"
desc = "Curso básico de Stellar"

[[CURRENCIES]]
code = "MKT102"
issuer = "GAVOA6QBBSDKH3NMD2LQIJBXBT3CZPG4CHFGMNDZ4PJ63T7XVK5VKGF6"
display_decimals = 0
name = "Growth Marketing"
image = "https://raw.githubusercontent.com/ernestocripto/SkillGraph/main/assets/MKT102.png"
desc = "Estrategias de Growth Marketing en Web3"
